services:
  zdashboard:
    build: .
    container_name: zdashboard
    ports:
      - "3100:3100"
    environment:
      - PORT=3100
      - HOST=0.0.0.0
      - DB_PATH=/db/zdb.db
      - AUDIO_DIR=/audio
    volumes:
      - ./zdb.db:/db/zdb.db
      - ./audio:/audio
