#!/usr/bin/env bash
# =============================================================================
# container2run (c2r) - Pack any Docker container into a portable .run file
# Usage:
#   c2r build   -f <docker-compose.yml> -o <output.run> [-i <image|file.tar>] [-d]
#   c2r build   -f <docker-compose.yml> -o <output.run> --pull [-d]
#   c2r capture <container_name> -o <output.run> [-d]
#   c2r capture <container_name> -o <output.run> --pull [-d]
#   c2r version
# =============================================================================

set -euo pipefail

C2R_VERSION="0.2.1"
BOLD="\033[1m"
RED="\033[31m"
GREEN="\033[32m"
YELLOW="\033[33m"
CYAN="\033[36m"
RESET="\033[0m"

# =============================================================================
# Utilities
# =============================================================================

log_info()    { echo -e "${CYAN}[c2r]${RESET} $*"; }
log_success() { echo -e "${GREEN}[c2r] ✓${RESET} $*"; }
log_warn()    { echo -e "${YELLOW}[c2r] ⚠${RESET} $*"; }
log_error()   { echo -e "${RED}[c2r] ✗${RESET} $*" >&2; }
die()         { log_error "$*"; exit 1; }

require_cmd() {
    for cmd in "$@"; do
        command -v "$cmd" &>/dev/null || die "Required command not found: $cmd"
    done
}

# Fix #15: use stat for accurate byte count, then convert to MB
file_size_mb() {
    local file="$1"
    local bytes
    bytes=$(stat -c%s "$file" 2>/dev/null || stat -f%z "$file" 2>/dev/null || echo 0)
    echo $(( bytes / 1024 / 1024 ))
}

# =============================================================================
# Image origin detection
# =============================================================================

detect_image_origin() {
    local image="$1"
    local force_mode="${2:-}"   # "pull" or "" (default: embed)

    if [ "$force_mode" = "pull" ]; then
        log_info "Pull mode via --pull flag. Image will be pulled at runtime." >&2
        echo "pull"; return
    fi

    # Default: embed
    log_info "Embed mode (default). Image will be bundled into .run." >&2
    echo "embed"
}

# =============================================================================
# Generate start.sh
# $1: daemonize ("true" | "false")
#
# Strategy: the header (trap + compose command) is mode-specific and uses
# a double-quoted heredoc with interpolation. The body (image load, checks)
# is static and uses a single-quoted heredoc to avoid escaping every $.
# =============================================================================

generate_start_sh() {
    local daemonize="${1:-false}"

    # ── Mode-specific: header block ──────────────────────────────────────────
    if [ "$daemonize" = "true" ]; then
        cat <<HEADER
#!/usr/bin/env bash
# Auto-generated by container2run (c2r) — daemon mode (-d)
set -euo pipefail

BOLD="\033[1m"
RED="\033[31m"
GREEN="\033[32m"
YELLOW="\033[33m"
CYAN="\033[36m"
RESET="\033[0m"

log_info()    { echo -e "\${CYAN}[run]\${RESET} \$*"; }
log_success() { echo -e "\${GREEN}[run] ✓\${RESET} \$*"; }
log_warn()    { echo -e "\${YELLOW}[run] ⚠\${RESET} \$*"; }
log_error()   { echo -e "\${RED}[run] ✗\${RESET} \$*" >&2; }
die()         { log_error "\$*"; exit 1; }

SCRIPT_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
COMPOSE_FILE="\$SCRIPT_DIR/docker-compose.yml"
IMAGE_ARCHIVE="\$SCRIPT_DIR/image.tar.gz"
LOADED_IMAGES=()
IMAGE_PREEXISTED=false

# Daemon mode: no cleanup trap.
# Image is retained on the host after exit.
# To stop the service: docker compose -f "\$COMPOSE_FILE" down
HEADER
    else
        cat <<HEADER
#!/usr/bin/env bash
# Auto-generated by container2run (c2r) — blocking mode
set -euo pipefail

BOLD="\033[1m"
RED="\033[31m"
GREEN="\033[32m"
YELLOW="\033[33m"
CYAN="\033[36m"
RESET="\033[0m"

log_info()    { echo -e "\${CYAN}[run]\${RESET} \$*"; }
log_success() { echo -e "\${GREEN}[run] ✓\${RESET} \$*"; }
log_warn()    { echo -e "\${YELLOW}[run] ⚠\${RESET} \$*"; }
log_error()   { echo -e "\${RED}[run] ✗\${RESET} \$*" >&2; }
die()         { log_error "\$*"; exit 1; }

SCRIPT_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
COMPOSE_FILE="\$SCRIPT_DIR/docker-compose.yml"
IMAGE_ARCHIVE="\$SCRIPT_DIR/image.tar.gz"
LOADED_IMAGES=()
IMAGE_PREEXISTED=false

# Blocking mode: cleanup runs on any exit (Ctrl-C, kill, error).
cleanup() {
    echo ""
    log_info "Shutting down..."
    docker compose -f "\$COMPOSE_FILE" down 2>/dev/null || true

    if [ "\$IMAGE_PREEXISTED" = false ]; then
        for img in "\${LOADED_IMAGES[@]:-}"; do
            [ -z "\$img" ] && continue
            log_info "Removing embedded image: \$img"
            docker rmi "\$img" 2>/dev/null || \\
                log_warn "Could not remove '\$img' (may be used by another container)"
        done
    else
        log_info "Image pre-existed on this machine — skipping removal."
    fi

    log_success "Clean exit."
}

trap cleanup EXIT
HEADER
    fi

    # ── Static body (single-quoted heredoc — no escaping needed) ─────────────
    cat <<'BODY'

# =============================================================================
# Load embedded image if present
# =============================================================================

if [ -f "$IMAGE_ARCHIVE" ]; then
    log_info "Loading embedded image..."

    archived_image=$(tar -xOf "$IMAGE_ARCHIVE" manifest.json 2>/dev/null \
        | grep -oP '(?<="RepoTags":\[")[^"]+' | head -1 || true)

    if [ -n "$archived_image" ] && docker image inspect "$archived_image" &>/dev/null 2>&1; then
        # Determine if the tag is mutable (latest or no tag) — these are never protected
        archived_tag="${archived_image##*:}"
        if [ "$archived_tag" = "latest" ] || [ "$archived_tag" = "$archived_image" ]; then
            IMAGE_PREEXISTED=false
            log_info "Image '$archived_image' already exists (mutable tag) — will overwrite and remove on exit."
        else
            IMAGE_PREEXISTED=true
            log_warn "Image '$archived_image' already exists (pinned tag) — will not remove on exit."
        fi
    fi

    loaded_output=$(docker load < "$IMAGE_ARCHIVE" 2>&1)
    echo "$loaded_output"

    while IFS= read -r loaded_image; do
        [ -n "$loaded_image" ] && LOADED_IMAGES+=("$loaded_image")
    done < <(echo "$loaded_output" | grep -oP '(?<=Loaded image: ).+' || true)

    log_success "Loaded ${#LOADED_IMAGES[@]} image(s)."
fi

# =============================================================================
# Static parse: extract ${VAR} placeholders from compose file
# =============================================================================

extract_vars() {
    grep -oP '\$\{[A-Z0-9_]+\}' "$COMPOSE_FILE" \
        | grep -oP '[A-Z0-9_]+' \
        | sort -u
}

# =============================================================================
# Variable check & interactive prompt
# =============================================================================

check_and_prompt_vars() {
    local vars
    vars=$(extract_vars || true)

    if [ -z "$vars" ]; then
        log_info "No variable placeholders found in compose file."
        return
    fi

    local missing=()
    for var in $vars; do
        if [ -z "${!var:-}" ]; then
            missing+=("$var")
        fi
    done

    if [ ${#missing[@]} -eq 0 ]; then
        log_success "All required variables are set."
        return
    fi

    echo ""
    log_warn "The following required variables are not set:"
    echo ""
    for var in "${missing[@]}"; do
        echo -e "  ${BOLD}${var}${RESET}"
    done
    echo ""

    for var in "${missing[@]}"; do
        echo -ne "${CYAN}?${RESET} Enter value for ${BOLD}${var}${RESET}: "
        read -r value </dev/tty
        export "${var}=${value}"
    done

    log_success "All variables collected."
}

# =============================================================================
# Port conflict check
# =============================================================================

check_ports() {
    local ports
    ports=$(awk '
        /^[[:space:]]+ports:/ { in_ports=1; next }
        in_ports && /^[[:space:]]+-/ {
            if (match($0, /[0-9]+:[0-9]+/)) {
                val = substr($0, RSTART, RLENGTH)
                split(val, parts, ":")
                print parts[1]
            }
            next
        }
        in_ports && /^[[:space:]]+[a-z_]+:/ { in_ports=0 }
    ' "$COMPOSE_FILE" | sort -u || true)

    for port in $ports; do
        if lsof -iTCP:"$port" -sTCP:LISTEN &>/dev/null 2>&1 || \
           ss -tlnp 2>/dev/null | grep -qP ":${port}(?=[^0-9])"; then
            log_warn "Port ${BOLD}${port}${RESET} is already in use."
            echo -ne "${CYAN}?${RESET} Enter alternative port for ${BOLD}${port}${RESET}: "
            read -r new_port </dev/tty
            sed -i -E "s/(\"| )${port}:([0-9])/\1${new_port}:\2/g" "$COMPOSE_FILE"
            log_success "Port remapped: ${port} → ${new_port}"
        fi
    done
}

# =============================================================================
# Volume path check (handles both files and directories)
# =============================================================================

check_volumes() {
    local paths
    paths=$(awk '
        /^[[:space:]]+volumes:/ { in_vols=1; next }
        in_vols && /^[[:space:]]+-/ {
            if (match($0, /- +([\.\/][^:]*):/, arr)) {
                gsub(/^[[:space:]]+/, "", arr[1])
                print arr[1]
            }
            next
        }
        in_vols && /^[[:space:]]+[a-z_]+:/ { in_vols=0 }
    ' "$COMPOSE_FILE" | sort -u || true)

    for path in $paths; do
        local resolved="$path"
        if [[ "$path" != /* ]]; then
            resolved="$(pwd)/${path}"
            sed -i "s|- ${path}:|- ${resolved}:|g" "$COMPOSE_FILE"
            path="$resolved"
        fi

        if [ ! -e "$path" ]; then
            local mount_type="directory"
            local basename="${path##*/}"
            if [[ "$basename" == *.* ]]; then
                mount_type="file"
            fi

            log_warn "Volume ${mount_type} does not exist: ${BOLD}${path}${RESET}"

            if [ "$mount_type" = "file" ]; then
                echo -e "  ${BOLD}1)${RESET} Create an empty file at this path"
                echo -e "  ${BOLD}2)${RESET} Specify a different file path"
            else
                echo -e "  ${BOLD}1)${RESET} Auto-create the directory"
                echo -e "  ${BOLD}2)${RESET} Specify a different path"
            fi
            echo -n "Choice [1/2]: "
            read -r choice </dev/tty

            case "$choice" in
                2)
                    echo -ne "${CYAN}?${RESET} Enter replacement path: "
                    read -r new_path </dev/tty
                    new_path="${new_path/#\~/$HOME}"
                    sed -i "s|- ${path}:|- ${new_path}:|g" "$COMPOSE_FILE"
                    log_success "Volume remapped: ${path} → ${new_path}"
                    ;;
                *)
                    if [ "$mount_type" = "file" ]; then
                        mkdir -p "$(dirname "$path")"
                        touch "$path"
                        log_success "Created empty file: ${path}"
                    else
                        mkdir -p "$path"
                        log_success "Created directory: ${path}"
                    fi
                    ;;
            esac
        fi
    done
}

# =============================================================================
# Main
# =============================================================================

echo ""
echo -e "${BOLD}container2run${RESET} — starting service"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

check_and_prompt_vars
check_ports
check_volumes

echo ""
log_success "All checks passed. Starting service..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

BODY

    # ── Mode-specific: final compose command ─────────────────────────────────
    if [ "$daemonize" = "true" ]; then
        echo 'docker compose -f "$COMPOSE_FILE" down 2>/dev/null || true'
        echo 'docker compose -f "$COMPOSE_FILE" up -d'
        echo 'log_success "Service started in background."'
        echo 'log_info "To stop: docker compose -f \"$COMPOSE_FILE\" down"'
    else
        echo 'docker compose -f "$COMPOSE_FILE" down 2>/dev/null || true'
        echo 'docker compose -f "$COMPOSE_FILE" up'
    fi
}

# =============================================================================
# Build: docker-compose.yml → .run
# =============================================================================

build_run_file() {
    local compose_file="$1"
    local output_file="$2"
    local force_mode="${3:-}"
    local daemonize="${4:-false}"
    local image_override="${5:-}"   # -i <image_name|file.tar>

    require_cmd docker makeself

    [ -f "$compose_file" ] || die "Compose file not found: $compose_file"

    local images
    images=$(grep -E '^\s+image:' "$compose_file" \
        | awk '{print $2}' | tr -d '"' | sed 's/\r$//' | sort -u)
    [ -n "$images" ] || die "No 'image:' field found in compose file."

    log_info "Building .run from: $compose_file"
    [ "$daemonize" = "true" ] && log_info "Mode: ${YELLOW}daemon${RESET} (up -d, no cleanup)"
    log_info "Detected image(s):"
    while IFS= read -r img; do echo "    - $img"; done <<< "$images"

    local tmpdir
    tmpdir=$(mktemp -d)
    # shellcheck disable=SC2064
    trap "rm -rf '$tmpdir'" EXIT

    cp "$compose_file" "$tmpdir/docker-compose.yml"
    generate_start_sh "$daemonize" > "$tmpdir/start.sh"
    chmod +x "$tmpdir/start.sh"

    local embed_images=()
    while IFS=$'\r\n' read -r image; do
        local origin
        origin=$(detect_image_origin "$image" "$force_mode")
        if [ "$origin" = "embed" ]; then
            embed_images+=("$image")
        fi
    done <<< "$images"

    if [ ${#embed_images[@]} -gt 0 ]; then
        # Pre-check: all images must exist in local daemon
        for img in "${embed_images[@]}"; do
            docker image inspect "$img" &>/dev/null || die "Image not found in local daemon: $img\n       Please build or pull it first: docker build -t $img ."
        done
        log_info "Saving ${#embed_images[@]} image(s) into single archive (this may take a while)..."
        docker save "${embed_images[@]}" | gzip > "$tmpdir/image.tar.gz"
        local size_mb
        size_mb=$(file_size_mb "$tmpdir/image.tar.gz")
        log_success "Archive ready: ~${size_mb}MB (${#embed_images[@]} image(s))"
    fi

    local app_name
    app_name=$(basename "$output_file" .run)

    log_info "Packaging with makeself..."
    makeself --gzip "$tmpdir" "$output_file" "$app_name (container2run)" ./start.sh

    log_success "Created: ${BOLD}${output_file}${RESET}"
    ls -lh "$output_file"
}

# =============================================================================
# Capture: running container → compose → .run
# =============================================================================

capture_container() {
    local container_name="$1"
    local output_file="$2"
    local force_mode="${3:-}"
    local daemonize="${4:-false}"

    require_cmd docker makeself

    docker inspect "$container_name" &>/dev/null \
        || die "Container not found: $container_name"

    log_info "Inspecting container: ${BOLD}${container_name}${RESET}"
    [ "$daemonize" = "true" ] && log_info "Mode: ${YELLOW}daemon${RESET} (up -d, no cleanup)"

    local image
    image=$(docker inspect "$container_name" --format='{{.Config.Image}}')

    local env_block=""
    while IFS= read -r line; do
        [ -z "$line" ] && continue
        local key value
        key="${line%%=*}"
        value="${line#*=}"
        case "$key" in PATH|HOSTNAME|HOME|TERM|no_proxy|NO_PROXY) continue ;; esac
        env_block+="      ${key}: \"${value}\""$'\n'
    done < <(docker inspect "$container_name" \
        --format='{{range .Config.Env}}{{println .}}{{end}}' 2>/dev/null || true)

    local port_block=""
    while IFS= read -r line; do
        [ -z "$line" ] && continue
        port_block+="      - \"${line}\""$'\n'
    done < <(docker inspect "$container_name" \
        --format='{{range $p, $conf := .HostConfig.PortBindings}}{{if $conf}}{{(index $conf 0).HostPort}}:{{$p}}{{"\n"}}{{end}}{{end}}' \
        2>/dev/null | sed 's|/tcp||g; s|/udp||g' || true)

    local vol_block=""
    while IFS= read -r line; do
        [ -z "$line" ] && continue
        [[ "$line" == :* ]] && continue
        vol_block+="      - ${line}"$'\n'
    done < <(docker inspect "$container_name" \
        --format='{{range .Mounts}}{{.Source}}:{{.Destination}}{{"\n"}}{{end}}' \
        2>/dev/null || true)

    local service_name
    service_name=$(echo "$container_name" \
        | sed 's/[^a-zA-Z0-9]/_/g' | tr '[:upper:]' '[:lower:]')

    local tmpdir
    tmpdir=$(mktemp -d)
    # shellcheck disable=SC2064
    trap "rm -rf '$tmpdir'" EXIT

    {
        echo "# Generated by container2run (c2r) from container: ${container_name}"
        echo ""
        echo "services:"
        echo "  ${service_name}:"
        echo "    image: ${image}"
        if [ -n "$env_block" ]; then
            echo "    environment:"
            printf '%s' "$env_block"
        fi
        if [ -n "$port_block" ]; then
            echo "    ports:"
            printf '%s' "$port_block"
        fi
        if [ -n "$vol_block" ]; then
            echo "    volumes:"
            printf '%s' "$vol_block"
        fi
    } > "$tmpdir/docker-compose.yml"

    log_success "Generated docker-compose.yml:"
    echo ""
    cat "$tmpdir/docker-compose.yml"
    echo ""

    generate_start_sh "$daemonize" > "$tmpdir/start.sh"
    chmod +x "$tmpdir/start.sh"

    local origin
    origin=$(detect_image_origin "$image" "$force_mode")

    if [ "$origin" = "embed" ]; then
        if ! docker image inspect "$image" &>/dev/null; then
            die "Image '$image' not found locally. Pull or build it first."
        fi
        log_info "Saving image (this may take a while)..."
        docker image inspect "$image" &>/dev/null || die "Image not found in local daemon: $image\n       Please build or pull it first: docker build -t $image ."
        docker save "$image" | gzip > "$tmpdir/image.tar.gz"
        local size_mb
        size_mb=$(file_size_mb "$tmpdir/image.tar.gz")
        log_success "Image saved. Archive: ~${size_mb}MB"
    fi

    local app_name
    app_name=$(basename "$output_file" .run)

    log_info "Packaging with makeself..."
    makeself --gzip "$tmpdir" "$output_file" "$app_name (container2run)" ./start.sh

    log_success "Created: ${BOLD}${output_file}${RESET}"
    ls -lh "$output_file"
}

# =============================================================================
# CLI entry point
# =============================================================================

usage() {
    echo -e "${BOLD}container2run (c2r) v${C2R_VERSION}${RESET}"
    echo ""
    echo "Pack any Docker container into a portable self-contained .run file."
    echo ""
    echo -e "${BOLD}Usage:${RESET}"
    echo "  c2r build   -f <compose> -o <output.run> [-i <image|file.tar>] [-d]"
    echo "  c2r build   -f <compose> -o <output.run> --pull [-d]"
    echo "  c2r capture <container>  -o <output.run> [-d]"
    echo "  c2r capture <container>  -o <output.run> --pull [-d]"
    echo "  c2r version"
    echo ""
    echo -e "${BOLD}Commands:${RESET}"
    echo "  build     Pack a docker-compose.yml into a .run file"
    echo "  capture   Capture a running container into a .run file"
    echo "  version   Show version"
    echo ""
    echo -e "${BOLD}Options:${RESET}"
    echo "  -f        Path to docker-compose.yml (build only)"
    echo "  -o        Output .run file path"
    echo "  -i        Image name or path to .tar file (build only)"
    echo "            If file: used directly, skip docker save"
    echo "            If name: overrides compose image, docker save from daemon"
    echo "  --pull    Pull image from registry at runtime (default: embed)"
    echo "  -d        Daemon mode: generated .run uses 'up -d', skips cleanup"
    echo "  -h        Show this help"
    echo ""
    echo -e "${BOLD}Examples:${RESET}"
    echo "  c2r build -f ./docker-compose.yml -o myapp.run"
    echo "  c2r build -f ./docker-compose.yml -i myapp:v2 -o myapp.run"
    echo "  c2r build -f ./docker-compose.yml -i ./myapp.tar -o myapp.run"
    echo "  c2r build -f ./docker-compose.yml -o myapp.run -d"
    echo "  c2r build -f ./docker-compose.yml -o myapp.run --pull"
    echo "  c2r capture my_nginx -o nginx_backup.run"
    echo "  c2r capture my_nginx -o nginx_backup.run -d"
}

main() {
    [ $# -eq 0 ] && { usage; exit 0; }

    local subcommand="$1"
    shift

    case "$subcommand" in
        build)
            local compose_file="" output_file="" force_mode="" daemonize="false" image_override=""
            while [ $# -gt 0 ]; do
                case "$1" in
                    -f)      compose_file="$2"; shift 2 ;;
                    -o)      output_file="$2";  shift 2 ;;
                    -i)      image_override="$2"; shift 2 ;;
                    --pull)  force_mode="pull";  shift ;;
                    -d)      daemonize="true";   shift ;;
                    -h|--help) usage; exit 0 ;;
                    *) die "Unknown option: $1" ;;
                esac
            done
            [ -n "$compose_file" ] || die "Missing -f <docker-compose.yml>"
            [ -n "$output_file" ]  || die "Missing -o <output.run>"
            build_run_file "$compose_file" "$output_file" "$force_mode" "$daemonize" "$image_override"
            ;;

        capture)
            [ $# -ge 1 ] || die "Missing container name. Usage: c2r capture <name> -o <output.run>"
            local container_name="$1"; shift
            local output_file="" force_mode="" daemonize="false"
            while [ $# -gt 0 ]; do
                case "$1" in
                    -o)      output_file="$2";  shift 2 ;;
                    --pull)  force_mode="pull";  shift ;;
                    -d)      daemonize="true";   shift ;;
                    -h|--help) usage; exit 0 ;;
                    *) die "Unknown option: $1" ;;
                esac
            done
            [ -n "$output_file" ] || die "Missing -o <output.run>"
            capture_container "$container_name" "$output_file" "$force_mode" "$daemonize"
            ;;

        version|-v|--version)
            echo "container2run (c2r) v${C2R_VERSION}"
            ;;

        -h|--help|help)
            usage
            ;;

        *)
            log_error "Unknown command: $subcommand"
            usage; exit 1
            ;;
    esac
}

main "$@"
